public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        perguntaLabel = new javax.swing.JLabel();
        perguntaTextField = new javax.swing.JTextField();
        alternativa_aLabel = new javax.swing.JLabel();
        alternativa_aTextField = new javax.swing.JTextField();
        alternativa_bLabel = new javax.swing.JLabel();
        alternativa_bTextField = new javax.swing.JTextField();
        alternativa_cLabel = new javax.swing.JLabel();
        alternativa_cTextField = new javax.swing.JTextField();
        alternativa_dLabel = new javax.swing.JLabel();
        alternativa_dTextField = new javax.swing.JTextField();
        respostaLabel = new javax.swing.JLabel();
        respostaAdmTextField = new javax.swing.JTextField();
        dificuldadeLabel = new javax.swing.JLabel();
        dificuldadeAdmTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idAdmTextField = new javax.swing.JTextField();
        cancelarAdmButton = new javax.swing.JButton();
        verPerguntaButton = new javax.swing.JButton();
        criarAdmButton = new javax.swing.JButton();
        atualizarAdmButton = new javax.swing.JButton();
        deletarAdmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento Code Quest");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("Gerenciar Perguntas");

        perguntaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perguntaLabel.setForeground(new java.awt.Color(0, 0, 0));
        perguntaLabel.setText("Pergunta");

        perguntaTextField.setBackground(new java.awt.Color(35, 143, 179));
        perguntaTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        perguntaTextField.setForeground(new java.awt.Color(0, 0, 0));
        perguntaTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        perguntaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perguntaTextFieldActionPerformed(evt);
            }
        });

        alternativa_aLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_aLabel.setForeground(new java.awt.Color(0, 0, 0));
        alternativa_aLabel.setText("Alternativa A");

        alternativa_aTextField.setBackground(new java.awt.Color(35, 143, 179));
        alternativa_aTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_aTextField.setForeground(new java.awt.Color(0, 0, 0));

        alternativa_bLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_bLabel.setForeground(new java.awt.Color(0, 0, 0));
        alternativa_bLabel.setText("Alternativa B");

        alternativa_bTextField.setBackground(new java.awt.Color(35, 143, 179));
        alternativa_bTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_bTextField.setForeground(new java.awt.Color(0, 0, 0));

        alternativa_cLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_cLabel.setForeground(new java.awt.Color(0, 0, 0));
        alternativa_cLabel.setText("Alternativa C");

        alternativa_cTextField.setBackground(new java.awt.Color(35, 143, 179));
        alternativa_cTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_cTextField.setForeground(new java.awt.Color(0, 0, 0));

        alternativa_dLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_dLabel.setForeground(new java.awt.Color(0, 0, 0));
        alternativa_dLabel.setText("Alternativa D");

        alternativa_dTextField.setBackground(new java.awt.Color(35, 143, 179));
        alternativa_dTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alternativa_dTextField.setForeground(new java.awt.Color(0, 0, 0));

        respostaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        respostaLabel.setForeground(new java.awt.Color(0, 0, 0));
        respostaLabel.setText("Resposta");

        respostaAdmTextField.setBackground(new java.awt.Color(35, 143, 179));
        respostaAdmTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        respostaAdmTextField.setForeground(new java.awt.Color(0, 0, 0));

        dificuldadeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dificuldadeLabel.setForeground(new java.awt.Color(0, 0, 0));
        dificuldadeLabel.setText("Dificuldade");

        dificuldadeAdmTextField.setBackground(new java.awt.Color(35, 143, 179));
        dificuldadeAdmTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dificuldadeAdmTextField.setForeground(new java.awt.Color(0, 0, 0));

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("ID (não necessário para criar)");

        idAdmTextField.setBackground(new java.awt.Color(35, 143, 179));
        idAdmTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idAdmTextField.setForeground(new java.awt.Color(0, 0, 0));

        cancelarAdmButton.setBackground(new java.awt.Color(51, 204, 255));
        cancelarAdmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelarAdmButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarAdmButton.setText("Cancelar");
        cancelarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAdmButtonActionPerformed(evt);
            }
        });

        verPerguntaButton.setBackground(new java.awt.Color(51, 204, 255));
        verPerguntaButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verPerguntaButton.setForeground(new java.awt.Color(0, 0, 0));
        verPerguntaButton.setText("Ver Pergunta");
        verPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPerguntaButtonActionPerformed(evt);
            }
        });

        criarAdmButton.setBackground(new java.awt.Color(51, 204, 255));
        criarAdmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        criarAdmButton.setForeground(new java.awt.Color(0, 0, 0));
        criarAdmButton.setText("Criar");
        criarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAdmButtonActionPerformed(evt);
            }
        });

        atualizarAdmButton.setBackground(new java.awt.Color(51, 204, 255));
        atualizarAdmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atualizarAdmButton.setForeground(new java.awt.Color(0, 0, 0));
        atualizarAdmButton.setText("Atualizar");
        atualizarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAdmButtonActionPerformed(evt);
            }
        });

        deletarAdmButton.setBackground(new java.awt.Color(51, 204, 255));
        deletarAdmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletarAdmButton.setForeground(new java.awt.Color(0, 0, 0));
        deletarAdmButton.setText("Deletar");
        deletarAdmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarAdmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(respostaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(251, 251, 251))
                            .addComponent(alternativa_dTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alternativa_dLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(230, 230, 230))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alternativa_cLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(230, 230, 230))
                            .addComponent(alternativa_cTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alternativa_bLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(231, 231, 231))
                            .addComponent(alternativa_bTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alternativa_aLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(230, 230, 230))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(perguntaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(250, 250, 250))
                            .addComponent(perguntaTextField)
                            .addComponent(alternativa_aTextField)
                            .addComponent(dificuldadeAdmTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dificuldadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(238, 238, 238))
                            .addComponent(respostaAdmTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(146, 146, 146))
                            .addComponent(idAdmTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(deletarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(atualizarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(criarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(tituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perguntaTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_aLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_aTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_bLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_bTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_cLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_cTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_dLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativa_dTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respostaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respostaAdmTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeAdmTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idAdmTextField)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletarAdmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perguntaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perguntaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perguntaTextFieldActionPerformed

    private void criarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAdmButtonActionPerformed
        //pegar dados inseridos nos TextFields
        String textopergunta = perguntaTextField.getText();
        String alt_a = alternativa_aTextField.getText();
        String alt_b = alternativa_bTextField.getText();
        String alt_c = alternativa_cTextField.getText();
        String alt_d = alternativa_dTextField.getText();
        String resposta = respostaAdmTextField.getText();
        String dificuldade = dificuldadeAdmTextField.getText();
        //instancia uma pergunta para inserir no bd
        Pergunta pergunta = new Pergunta(textopergunta, alt_a, alt_b, alt_c, alt_d, resposta, dificuldade);
        pergunta.criar(pergunta);
        //apagar TextFields para usar novamente
        perguntaTextField.setText("");
        alternativa_aTextField.setText("");
        alternativa_bTextField.setText("");
        alternativa_cTextField.setText("");
        alternativa_dTextField.setText("");
        respostaAdmTextField.setText("");
        dificuldadeAdmTextField.setText("");
        idAdmTextField.setText("");
    }//GEN-LAST:event_criarAdmButtonActionPerformed

    private void cancelarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAdmButtonActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setLocationRelativeTo(null);
        tl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarAdmButtonActionPerformed

    private void atualizarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAdmButtonActionPerformed
        String textopergunta = perguntaTextField.getText();
        String alt_a = alternativa_aTextField.getText();
        String alt_b = alternativa_bTextField.getText();
        String alt_c = alternativa_cTextField.getText();
        String alt_d = alternativa_dTextField.getText();
        String resposta = respostaAdmTextField.getText();
        String dificuldade = dificuldadeAdmTextField.getText();
        int id = Integer.parseInt(idAdmTextField.getText());
        //instancia uma pergunta para atualizar no bd
        Pergunta pergunta = new Pergunta(id,textopergunta, alt_a, alt_b, alt_c, alt_d, resposta, dificuldade);
        pergunta.atualizar(pergunta);
        //apagar TextFields para usar novamente
        perguntaTextField.setText("");
        alternativa_aTextField.setText("");
        alternativa_bTextField.setText("");
        alternativa_cTextField.setText("");
        alternativa_dTextField.setText("");
        respostaAdmTextField.setText("");
        dificuldadeAdmTextField.setText("");
        idAdmTextField.setText("");
    }//GEN-LAST:event_atualizarAdmButtonActionPerformed

    private void verPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPerguntaButtonActionPerformed
        int id = Integer.parseInt(idAdmTextField.getText());
        Pergunta pergunta = new Pergunta(id);
        pergunta.listar(pergunta);
        //apagar TextFields para usar novamente
        perguntaTextField.setText("");
        alternativa_aTextField.setText("");
        alternativa_bTextField.setText("");
        alternativa_cTextField.setText("");
        alternativa_dTextField.setText("");
        respostaAdmTextField.setText("");
        dificuldadeAdmTextField.setText("");
        idAdmTextField.setText("");
    }//GEN-LAST:event_verPerguntaButtonActionPerformed

    private void deletarAdmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarAdmButtonActionPerformed
        int id = Integer.parseInt(idAdmTextField.getText());
        Pergunta pergunta = new Pergunta(id);
        pergunta.deletar(pergunta);
        //apagar TextFields para usar novamente
        perguntaTextField.setText("");
        alternativa_aTextField.setText("");
        alternativa_bTextField.setText("");
        alternativa_cTextField.setText("");
        alternativa_dTextField.setText("");
        respostaAdmTextField.setText("");
        dificuldadeAdmTextField.setText("");
        idAdmTextField.setText("");
    }//GEN-LAST:event_deletarAdmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alternativa_aLabel;
    private javax.swing.JTextField alternativa_aTextField;
    private javax.swing.JLabel alternativa_bLabel;
    private javax.swing.JTextField alternativa_bTextField;
    private javax.swing.JLabel alternativa_cLabel;
    private javax.swing.JTextField alternativa_cTextField;
    private javax.swing.JLabel alternativa_dLabel;
    private javax.swing.JTextField alternativa_dTextField;
    private javax.swing.JButton atualizarAdmButton;
    private javax.swing.JButton cancelarAdmButton;
    private javax.swing.JButton criarAdmButton;
    private javax.swing.JButton deletarAdmButton;
    private javax.swing.JTextField dificuldadeAdmTextField;
    private javax.swing.JLabel dificuldadeLabel;
    private javax.swing.JTextField idAdmTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel perguntaLabel;
    private javax.swing.JTextField perguntaTextField;
    private javax.swing.JTextField respostaAdmTextField;
    private javax.swing.JLabel respostaLabel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton verPerguntaButton;
    // End of variables declaration//GEN-END:variables
}
